CONTROL_DESACTIVAR = 'control_desactivar'
PANTALLA_LCD_CONTROL = 'pantalla_lcd_control'
CONTROL_MOVIMIENTO = 'control_movimiento'
CONTROL_REMOTO = 'control_remoto'

CONTROL_DESACTIVAR_ACCION_DESACTIVAR = 'desactivar'
CONTROL_DESACTIVAR_ACCION_ACTIVAR = 'activar'

CONTROL_DESACTIVAR_PANTALLA_LCD_OK_ON = CONTROL_DESACTIVAR + ' OK ON'
CONTROL_DESACTIVAR_PANTALLA_LCD_OK_OFF = CONTROL_DESACTIVAR + ' OK OFF'
CONTROL_DESACTIVAR_PANTALLA_LCD_NOK = CONTROL_DESACTIVAR + ' NOK'

CONTROL_REMOTO_PANTALLA_LCD_OK = CONTROL_REMOTO + ' OK'
CONTROL_REMOTO_PANTALLA_LCD_BUSCANDO = CONTROL_REMOTO + ' BUSCANDO'
CONTROL_REMOTO_PANTALLA_LCD_NOK = CONTROL_REMOTO + ' NOK'

ACCION_CONTROL_PANTALLA_LCD_ON = PANTALLA_LCD_CONTROL + ' ON'
ACCION_CONTROL_PANTALLA_LCD_OFF = PANTALLA_LCD_CONTROL + ' OFF'